version: 1.0.{build}
branches:
  only:
  - main
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore src/Obs.Websocket.Reactive.sln
build:
  project: src/Obs.Websocket.Reactive.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
deploy:
  provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  server:
  api_key:
    secure: vh1Q9+c84PpqCQGl4hYycxoJunMSB9YpXGVJRp0KdP2VP2cU7kRoW08Qaf3mARd+
  skip_symbols: true
  symbol_server:
  artifact: /.*\.nupkg/
